In [8]:
import pandas as pd

pd.read_csv (r'C:\Users\ChoudAnt\Downloads\Aggregated_Metrics_By_Country_And_Subscriber_Status.csv')

,Video Title,External Video ID,Video Length,Thumbnail link,Country Code,Is Subscribed,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
0,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,HK,True,23,1,0,0,2,0,0.671870,39.640348,0
1,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,ME,True,3,0,0,0,0,0,0.498870,29.433333,0
2,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,RW,True,2,0,0,0,0,0,0.681780,40.225000,0
3,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,US,True,979,81,6,8,16,4,0.694854,40.996389,0
4,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,DE,False,75,3,0,1,0,0,0.661515,39.029373,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55287,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MM,False,1,0,0,0,0,0,0.622642,33.000000,0
55288,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SA,True,14,1,0,0,0,0,0.515569,27.325143,0
55289,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,DZ,False,2,0,0,0,0,0,0.782075,41.450000,0
55290,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MX,False,11,0,0,0,0,0,0.636178,33.717455,0
55291,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SR,True,1,0,0,0,0,0,0.985679,52.241000,0

In [9]:
df.isnull().sum()

Video Title                      0
External Video ID                0
Video Length                     0
Thumbnail link                   0
Country Code                   386
Is Subscribed                    0
Views                            0
Video Likes Added                0
Video Dislikes Added             0
Video Likes Removed              0
User Subscriptions Added         0
User Subscriptions Removed       0
Average View Percentage       1438
Average Watch Time            1438
User Comments Added              0
dtype: int64

In [ ]:
df1 = df.fillna({
    
    'date_added':' 16 april 2022',
    'Video Title':"joker",
})

In [36]:
print(df)

                                             Video Title External Video ID  \
0      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
1      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
2      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
3      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
4      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
...                                                  ...               ...
55287                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g
55288                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g
55289                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g
55290                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g
55291                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g

       Video Length                                    Thumbnail link  \
0                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
1                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
2                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
3                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
4                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
...             ...                                               ...
55287            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg
55288            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg
55289            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg
55290            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg
55291            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg

      Country Code  Is Subscribed  Views  Video Likes Added  \
0               HK           True     23                  1
1               ME           True      3                  0
2               RW           True      2                  0
3               US           True    979                 81
4               DE          False     75                  3
...            ...            ...    ...                ...
55287           MM          False      1                  0
55288           SA           True     14                  1
55289           DZ          False      2                  0
55290           MX          False     11                  0
55291           SR           True      1                  0

       Video Dislikes Added  Video Likes Removed  User Subscriptions Added  \
0                         0                    0                         2
1                         0                    0                         0
2                         0                    0                         0
3                         6                    8                        16
4                         0                    1                         0
...                     ...                  ...                       ...
55287                     0                    0                         0
55288                     0                    0                         0
55289                     0                    0                         0
55290                     0                    0                         0
55291                     0                    0                         0

       User Subscriptions Removed  Average View Percentage  \
0                               0                 0.671870
1                               0                 0.498870
2                               0                 0.681780
3                               4                 0.694854
4                               0                 0.661515
...                           ...                      ...
55287                           0                 0.622642
55288                           0                 0.515569
55289                           0                 0.782075
55290                           0                 0.636178
55291                           0                 0.985679

       Average Watch Time  User Comments Added
0               39.640348                    0
1               29.433333                    0
2               40.225000                    0
3               40.996389                    0
4               39.029373                    0
...                   ...                  ...
55287           33.000000                    0
55288           27.325143                    0
55289           41.450000                    0
55290           33.717455                    0
55291           52.241000                    0

[55292 rows x 15 columns]

In [17]:
df.count()

Video Title                   55292
External Video ID             55292
Video Length                  55292
Thumbnail link                55292
Country Code                  54906
Is Subscribed                 55292
Views                         55292
Video Likes Added             55292
Video Dislikes Added          55292
Video Likes Removed           55292
User Subscriptions Added      55292
User Subscriptions Removed    55292
Average View Percentage       53854
Average Watch Time            53854
User Comments Added           55292
dtype: int64

In [18]:
df

,Video Title,External Video ID,Video Length,Thumbnail link,Country Code,Is Subscribed,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
0,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,HK,True,23,1,0,0,2,0,0.671870,39.640348,0
1,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,ME,True,3,0,0,0,0,0,0.498870,29.433333,0
2,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,RW,True,2,0,0,0,0,0,0.681780,40.225000,0
3,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,US,True,979,81,6,8,16,4,0.694854,40.996389,0
4,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,DE,False,75,3,0,1,0,0,0.661515,39.029373,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55287,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MM,False,1,0,0,0,0,0,0.622642,33.000000,0
55288,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SA,True,14,1,0,0,0,0,0.515569,27.325143,0
55289,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,DZ,False,2,0,0,0,0,0,0.782075,41.450000,0
55290,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MX,False,11,0,0,0,0,0,0.636178,33.717455,0
55291,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SR,True,1,0,0,0,0,0,0.985679,52.241000,0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55292 entries, 0 to 55291
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Video Title                 55292 non-null  object
 1   External Video ID           55292 non-null  object
 2   Video Length                55292 non-null  int64
 3   Thumbnail link              55292 non-null  object
 4   Country Code                54906 non-null  object
 5   Is Subscribed               55292 non-null  bool
 6   Views                       55292 non-null  int64
 7   Video Likes Added           55292 non-null  int64
 8   Video Dislikes Added        55292 non-null  int64
 9   Video Likes Removed         55292 non-null  int64
 10  User Subscriptions Added    55292 non-null  int64
 11  User Subscriptions Removed  55292 non-null  int64
 12  Average View Percentage     53854 non-null  float64
 13  Average Watch Time          53854 non-null  float64
 14  User Comments Added         55292 non-null  int64
dtypes: bool(1), float64(2), int64(8), object(4)
memory usage: 6.0+ MB

In [22]:
df.tail()

,Video Title,External Video ID,Video Length,Thumbnail link,Country Code,Is Subscribed,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
55287,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MM,False,1,0,0,0,0,0,0.622642,33.000000,0
55288,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SA,True,14,1,0,0,0,0,0.515569,27.325143,0
55289,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,DZ,False,2,0,0,0,0,0,0.782075,41.450000,0
55290,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MX,False,11,0,0,0,0,0,0.636178,33.717455,0
55291,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SR,True,1,0,0,0,0,0,0.985679,52.241000,0

In [23]:
df.head()

,Video Title,External Video ID,Video Length,Thumbnail link,Country Code,Is Subscribed,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
0,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,HK,True,23,1,0,0,2,0,0.671870,39.640348,0
1,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,ME,True,3,0,0,0,0,0,0.498870,29.433333,0
2,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,RW,True,2,0,0,0,0,0,0.681780,40.225000,0
3,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,US,True,979,81,6,8,16,4,0.694854,40.996389,0
4,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,DE,False,75,3,0,1,0,0,0.661515,39.029373,0

In [24]:
df.describe()

,Video Length,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
count,55292.000000,55292.000000,55292.000000,55292.000000,55292.000000,55292.000000,55292.000000,53854.000000,53854.000000,55292.0
mean,896.678073,100.573157,4.239311,0.106055,0.175577,2.365279,0.053389,0.347821,205.297156,0.0
std,927.380801,1704.966002,65.291451,2.507351,3.601171,65.889539,0.766945,0.259734,206.542106,0.0
min,47.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,375.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.145948,85.442891,0.0
50%,545.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.320983,170.139725,0.0
75%,934.000000,27.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.486153,259.449958,0.0
max,5029.000000,285593.000000,9165.000000,399.000000,436.000000,9599.000000,103.000000,4.967797,5027.660000,0.0

In [25]:
df.any()

Video Title                    True
External Video ID              True
Video Length                   True
Thumbnail link                 True
Country Code                   True
Is Subscribed                  True
Views                          True
Video Likes Added              True
Video Dislikes Added           True
Video Likes Removed            True
User Subscriptions Added       True
User Subscriptions Removed     True
Average View Percentage        True
Average Watch Time             True
User Comments Added           False
dtype: bool

In [34]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
55287    False
55288    False
55289    False
55290    False
55291    False
Length: 55292, dtype: bool

In [31]:
df.duplicated().sum
print(df)

                                             Video Title External Video ID  \
0      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
1      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
2      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
3      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
4      ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...       OtqQYqRNDGI
...                                                  ...               ...
55287                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g
55288                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g
55289                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g
55290                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g
55291                #66DaysOfData - 3 Reasons to Start!       sICJ6a2wX5g

       Video Length                                    Thumbnail link  \
0                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
1                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
2                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
3                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
4                59  https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg
...             ...                                               ...
55287            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg
55288            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg
55289            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg
55290            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg
55291            53  https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg

      Country Code  Is Subscribed  Views  Video Likes Added  \
0               HK           True     23                  1
1               ME           True      3                  0
2               RW           True      2                  0
3               US           True    979                 81
4               DE          False     75                  3
...            ...            ...    ...                ...
55287           MM          False      1                  0
55288           SA           True     14                  1
55289           DZ          False      2                  0
55290           MX          False     11                  0
55291           SR           True      1                  0

       Video Dislikes Added  Video Likes Removed  User Subscriptions Added  \
0                         0                    0                         2
1                         0                    0                         0
2                         0                    0                         0
3                         6                    8                        16
4                         0                    1                         0
...                     ...                  ...                       ...
55287                     0                    0                         0
55288                     0                    0                         0
55289                     0                    0                         0
55290                     0                    0                         0
55291                     0                    0                         0

       User Subscriptions Removed  Average View Percentage  \
0                               0                 0.671870
1                               0                 0.498870
2                               0                 0.681780
3                               4                 0.694854
4                               0                 0.661515
...                           ...                      ...
55287                           0                 0.622642
55288                           0                 0.515569
55289                           0                 0.782075
55290                           0                 0.636178
55291                           0                 0.985679

       Average Watch Time  User Comments Added
0               39.640348                    0
1               29.433333                    0
2               40.225000                    0
3               40.996389                    0
4               39.029373                    0
...                   ...                  ...
55287           33.000000                    0
55288           27.325143                    0
55289           41.450000                    0
55290           33.717455                    0
55291           52.241000                    0

[55292 rows x 15 columns]

In [37]:
df.dropna()

,Video Title,External Video ID,Video Length,Thumbnail link,Country Code,Is Subscribed,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
0,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,HK,True,23,1,0,0,2,0,0.671870,39.640348,0
1,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,ME,True,3,0,0,0,0,0,0.498870,29.433333,0
2,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,RW,True,2,0,0,0,0,0,0.681780,40.225000,0
3,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,US,True,979,81,6,8,16,4,0.694854,40.996389,0
4,ðŸŒ¶ Hot Topics in Tech: Data Science Explained #...,OtqQYqRNDGI,59,https://i.ytimg.com/vi/OtqQYqRNDGI/hqdefault.jpg,DE,False,75,3,0,1,0,0,0.661515,39.029373,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55287,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MM,False,1,0,0,0,0,0,0.622642,33.000000,0
55288,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SA,True,14,1,0,0,0,0,0.515569,27.325143,0
55289,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,DZ,False,2,0,0,0,0,0,0.782075,41.450000,0
55290,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,MX,False,11,0,0,0,0,0,0.636178,33.717455,0
55291,#66DaysOfData - 3 Reasons to Start!,sICJ6a2wX5g,53,https://i.ytimg.com/vi/sICJ6a2wX5g/hqdefault.jpg,SR,True,1,0,0,0,0,0,0.985679,52.241000,0

In [38]:
len(df)

55292

In [39]:
df.sample()

,Video Title,External Video ID,Video Length,Thumbnail link,Country Code,Is Subscribed,Views,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,User Subscriptions Removed,Average View Percentage,Average Watch Time,User Comments Added
37365,How I Got My First Data Science Internship (An...,T77uVbLhroQ,633,https://i.ytimg.com/vi/T77uVbLhroQ/hqdefault.jpg,KW,True,7,0,0,0,0,0,0.521555,330.144429,0